const dummyUsers = [
  {
    id: 1,
    username: "user1",
    name: "Rahul Kumar",
    email: "rahul@example.com",
    password: "password1",
  },
  {
    id: 2,
    username: "user2",
    name: "Priya Sharma",
    email: "priya@example.com",
    password: "password2",
  },
  {
    id: 3,
    username: "user3",
    name: "Amit Patel",
    email: "amit@example.com",
    password: "password3",
  },
  {
    id: 4,
    username: "user4",
    name: "Nisha Singh",
    email: "nisha@example.com",
    password: "password4",
  },
  {
    id: 5,
    username: "user5",
    name: "Rohit Gupta",
    email: "rohit@example.com",
    password: "password5",
  },
  {
    id: 6,
    username: "user6",
    name: "Pooja Verma",
    email: "pooja@example.com",
    password: "password6",
  },
  {
    id: 7,
    username: "user7",
    name: "Vikram Yadav",
    email: "vikram@example.com",
    password: "password7",
  },
  {
    id: 8,
    username: "user8",
    name: "Anjali Mishra",
    email: "anjali@example.com",
    password: "password8",
  },
  {
    id: 9,
    username: "user9",
    name: "Suresh Tiwari",
    email: "suresh@example.com",
    password: "password9",
  },
  {
    id: 10,
    username: "user10",
    name: "Sneha Reddy",
    email: "sneha@example.com",
    password: "password10",
  },
  {
    id: 11,
    username: "user11",
    name: "Rajesh Kumar",
    email: "rajesh@example.com",
    password: "password11",
  },
  {
    id: 12,
    username: "user12",
    name: "Divya Jain",
    email: "divya@example.com",
    password: "password12",
  },
  {
    id: 13,
    username: "user13",
    name: "Manoj Singhania",
    email: "manoj@example.com",
    password: "password13",
  },
  {
    id: 14,
    username: "user14",
    name: "Kavita Srivastava",
    email: "kavita@example.com",
    password: "password14",
  },
  {
    id: 15,
    username: "user15",
    name: "Aditya Choudhury",
    email: "aditya@example.com",
    password: "password15",
  },
  {
    id: 16,
    username: "user16",
    name: "Neha Malhotra",
    email: "neha@example.com",
    password: "password16",
  },
  {
    id: 17,
    username: "user17",
    name: "Raj Kapoor",
    email: "raj@example.com",
    password: "password17",
  },
  {
    id: 18,
    username: "user18",
    name: "Anita Das",
    email: "anita@example.com",
    password: "password18",
  },
  {
    id: 19,
    username: "user19",
    name: "Ankit Sharma",
    email: "ankit@example.com",
    password: "password19",
  },
  {
    id: 20,
    username: "user20",
    name: "Deepika Khanna",
    email: "deepika@example.com",
    password: "password20",
  },
];

module.exports = dummyUsers;
