db.HindiSongs.insertMany([
  {
    id: 1,
    title: "Tum Hi Ho",
    artist: "Arijit Singh",
    liked: true,
    recent: true,
    top: true,
  },
  {
    id: 2,
    title: "Gerua",
    artist: "Arijit Singh, Antara Mitra",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 3,
    title: "Ae Dil Hai Mushkil",
    artist: "Arijit Singh",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 4,
    title: "Channa Mereya",
    artist: "Arijit Singh",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 5,
    title: "Jeena Jeena",
    artist: "Atif Aslam",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 6,
    title: "Bolna",
    artist: "Arijit Singh, Asees Kaur",
    liked: false,
    recent: false,
    top: true,
  },
  {
    id: 7,
    title: "Ishq Wala Love",
    artist: "Salim Merchant, Neeti Mohan, Shekhar Ravjiani",
    liked: true,
    recent: false,
    top: true,
  },
  {
    id: 8,
    title: "Tera Ban Jaunga",
    artist: "Tulsi Kumar, Akhil Sachdeva",
    liked: true,
    recent: false,
    top: true,
  },
  {
    id: 9,
    title: "Muskurane Ki Wajah Tum Ho",
    artist: "Arijit Singh",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 10,
    title: "Dil Diyan Gallan",
    artist: "Atif Aslam",
    liked: false,
    recent: true,
    top: true,
  },
  {
    id: 11,
    title: "Ae Watan",
    artist: "Arijit Singh",
    liked: false,
    recent: false,
    top: false,
  },
  {
    id: 12,
    title: "Tera Fitoor",
    artist: "Arijit Singh",
    liked: true,
    recent: true,
    top: true,
  },
  {
    id: 13,
    title: "Ishq Di Chashni",
    artist: "Arijit Singh",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 14,
    title: "Zaalima",
    artist: "Arijit Singh, Harshdeep Kaur",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 15,
    title: "Janam Janam",
    artist: "Arijit Singh, Antara Mitra",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 16,
    title: "Tum Se Hi",
    artist: "Mohit Chauhan",
    liked: false,
    recent: true,
    top: true,
  },
  {
    id: 17,
    title: "Agar Tum Saath Ho",
    artist: "Alka Yagnik, Arijit Singh",
    liked: false,
    recent: false,
    top: true,
  },
  {
    id: 18,
    title: "Jiya",
    artist: "Arijit Singh",
    liked: true,
    recent: false,
    top: true,
  },
  {
    id: 19,
    title: "Tum Jo Aaye",
    artist: "Rahat Fateh Ali Khan, Tulsi Kumar",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 20,
    title: "Main Rang Sharbaton Ka",
    artist: "Atif Aslam, Chinmayi Sripaada",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 21,
    title: "Hamari Adhuri Kahani",
    artist: "Arijit Singh",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 22,
    title: "Raabta",
    artist: "Arijit Singh, Nikhita Gandhi",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 23,
    title: "Itni Si Baat Hai",
    artist: "Arijit Singh, Antara Mitra",
    liked: false,
    recent: true,
    top: true,
  },
  {
    id: 24,
    title: "Samjhawan",
    artist: "Arijit Singh, Shreya Ghoshal",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 25,
    title: "Dil Diyan Gallan",
    artist: "Atif Aslam",
    liked: false,
    recent: true,
    top: true,
  },
  {
    id: 26,
    title: "Tujhe Kitna Chahne Lage",
    artist: "Arijit Singh",
    liked: true,
    recent: false,
    top: true,
  },
  {
    id: 27,
    title: "Bekhayali",
    artist: "Arijit Singh",
    liked: false,
    recent: false,
    top: true,
  },
  {
    id: 28,
    title: "Mere Sohneya",
    artist: "Sachet Tandon, Parampara Thakur",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 29,
    title: "Pal Pal Dil Ke Paas",
    artist: "Arijit Singh",
    liked: true,
    recent: false,
    top: true,
  },
  {
    id: 30,
    title: "Bol Do Na Zara",
    artist: "Armaan Malik",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 31,
    title: "Laal Ishq",
    artist: "Arijit Singh",
    liked: true,
    recent: false,
    top: true,
  },
  {
    id: 32,
    title: "Tum Mile",
    artist: "Neeraj Shridhar",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 33,
    title: "Tum Se Hi",
    artist: "Mohit Chauhan",
    liked: false,
    recent: true,
    top: true,
  },
  {
    id: 34,
    title: "Lambiyaan Si Judaiyaan",
    artist: "Arijit Singh, Shadab Faridi, Altamash Faridi",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 35,
    title: "Enna Sona",
    artist: "Arijit Singh",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 36,
    title: "Tera Yaar Hoon Main",
    artist: "Arijit Singh",
    liked: true,
    recent: true,
    top: true,
  },
  {
    id: 37,
    title: "Dil Diyan Gallan",
    artist: "Atif Aslam",
    liked: false,
    recent: false,
    top: true,
  },
  {
    id: 38,
    title: "Tum Jo Aaye",
    artist: "Rahat Fateh Ali Khan, Tulsi Kumar",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 39,
    title: "Main Rang Sharbaton Ka",
    artist: "Atif Aslam, Chinmayi Sripaada",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 40,
    title: "Hamari Adhuri Kahani",
    artist: "Arijit Singh",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 41,
    title: "Raabta",
    artist: "Arijit Singh, Nikhita Gandhi",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 42,
    title: "Itni Si Baat Hai",
    artist: "Arijit Singh, Antara Mitra",
    liked: false,
    recent: true,
    top: true,
  },
  {
    id: 43,
    title: "Samjhawan",
    artist: "Arijit Singh, Shreya Ghoshal",
    liked: true,
    recent: false,
    top: false,
  },
  {
    id: 44,
    title: "Dil Diyan Gallan",
    artist: "Atif Aslam",
    liked: false,
    recent: true,
    top: true,
  },
  {
    id: 45,
    title: "Tujhe Kitna Chahne Lage",
    artist: "Arijit Singh",
    liked: true,
    recent: false,
    top: true,
  },
  {
    id: 46,
    title: "Bekhayali",
    artist: "Arijit Singh",
    liked: false,
    recent: false,
    top: true,
  },
  {
    id: 47,
    title: "Mere Sohneya",
    artist: "Sachet Tandon, Parampara Thakur",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 48,
    title: "Pal Pal Dil Ke Paas",
    artist: "Arijit Singh",
    liked: true,
    recent: false,
    top: true,
  },
  {
    id: 49,
    title: "Bol Do Na Zara",
    artist: "Armaan Malik",
    liked: false,
    recent: true,
    top: false,
  },
  {
    id: 50,
    title: "Laal Ishq",
    artist: "Arijit Singh",
    liked: true,
    recent: false,
    top: true,
  },
]);
